### ISSUE TITLE
分享监测任务：B站UP主视频更新

### ISSUE THREAD

**Issue by Ar-Hyk** [easychen/awesome-checkchan#2]
- B站UP主视频更新
  思路：获取UP主页的第一条视频标题
  - 演示
  [罗小黑战记  https://space.bilibili.com/5632230/](https://space.bilibili.com/5632230/)
![image](https://user-images.githubusercontent.com/55748412/172876166-351c3978-23c7-4ec7-97c9-0a3acd4166ee.png)
  - 任务编码
` checkchan://title=UP_%E7%BD%97%E5%B0%8F%E9%BB%91%E6%88%98%E8%AE%B0&url=https%3A%2F%2Fspace.bilibili.com%2F5632230%2F&path=%23page-index%20%3E%20div.col-1%20%3E%20div.section.video.full-rows%20%3E%20div%20%3E%20div%3Anth-child(1)%20%3E%20a.title&type=dom&code=200&json_data_format=form&rss_field=title&delay=0&retry=10&cron=*%20*%20*%20*%20*&when=change&compare_type=all&compare_op=ne&compare_value=*%E4%B8%8A%E6%AC%A1%E7%9B%91%E6%B5%8B%E8%BF%94%E5%9B%9E%E5%80%BC*&shell_type=javascript`
  - 改为其他UP主
粘贴任务到Check酱后修改**URL**中的**/5632230/**里的的数字，改为对应为UP主UID
![image](https://user-images.githubusercontent.com/55748412/172878499-110486bb-8711-448e-9c9c-8a2d50b953e8.png)
    - 获取UP主UID
挺简单的吧……不写了
------ 
> 不知道格式对不对，（dog）

**Comment by easychen** [comment]
感谢分享呀，我整理下合并进去。

**Comment by easychen** [comment]
已合并到首页，感谢分享。
